// Setting for autoGenerated project colors
// let useAutogeneratedColors = true;

// Manual dictionary of project names/regex and corresponding colors
const projectColors = new Map([
    ["Achilles", "hsl(30, 60%, 90%)" ],
    ["Magpie", "hsl(90, 60%, 90%)" ],
    [/Sandpiper.*\d+/i, "hsl(120, 60%, 90%)"]
]);

// Below: WIP Code for automatic colour coding via extraction and hashing of project name. 

// const extractProjectFamily = (projectName) => {
//   if (!projectName) return "";
//   let projectFamilyRegex = /^(\[.*\]\s*)?(rate and review:\s*)?(\w+)/gim
//   console.log(projectName.match(projectFamilyRegex));
//   let projectFamilyMatch = projectName.match(projectFamilyRegex);
//   let [isPriority, isRateAndReview, projectFamily] = projectFamilyMatch;
//   return projectFamily;
// }

// const generateColorForProjectFamilyName = (projectName) => {

//   //Isolate first word to find project family. 
//   let projectFamily = extractProjectFamily(projectName);

//   //Generate a colour based on a hash of the project family. 
//   //This should mean that each project family will have a certain auto-generated and stable colour, without manually setting it for every family. 

//   let hash = 0;
//   for (let i = 0; i < projectFamily.length; i++) {
//     hash = projectFamily.charCodeAt(i) + ((hash << 5) - hash);
//   }

//   const hue = hash % 360; // Ensure hue is within 0-360
//   const saturation = 80 + (hash % 20); // Some variation in saturation
//   const lightness = 50; // Keep lightness consistent for readability

//   return `hsl(${hue}, ${saturation}%, ${lightness}%)`;
// }

function isProjectNameMatch(projectName, key) {
  if (typeof key === 'string') {
    return projectName.includes(key);
  } else if (key instanceof RegExp) {
    return key.test(projectName);
  }
  return false; // Default to false if the key is not a string or RegExp
}

function highlightProjectRows() {
  const projectRows = document.querySelectorAll('tbody tr');

  projectRows.forEach(row => {
    const projectNameCell = row.querySelector('td:first-child a');
    const projectName = projectNameCell.textContent;

    // Auto-Generate Colours - commented out for now. 
    // default color is generated from family name. 
    // if (useAutogeneratedColors) {
    //   row.style.backgroundColor = generateColorForProjectFamilyName(projectFamily);
    // }

    for (const [key, color] of Array.from(projectColors)) {
      if (isProjectNameMatch(projectName, key)) {
        row.style.backgroundColor = color;
      }
    }
  }
  );
}
  
highlightProjectRows(); 